version: '3.2'

services:
  nginx-proxy:
    image: nginx:latest
    env_file:
       - .env
    volumes:
      - ./proxy-template.conf:/etc/nginx/templates/default.conf.template:ro
    environment:
      - SOURCE_PROTOCOL=${SOURCE_PROTOCOL:-https}
    ports:
      - "${DESTINATION_PORT:-8001}:80"
