version: '3.2'

services:
  nginx-proxy:
    image: nginx:latest
    env_file:
       - .env
    volumes:
      - ./templates:/etc/nginx/templates:ro
    ports:
      - "${DESTINATION_PORT:-8001}:80"
